volumes:
  subsquid-db:

services:
  pg:
    image: postgres:15-alpine
    container_name: jelly_pg
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "6432:5432"
    volumes:
      - subsquid-db:/var/lib/postgresql/data:delegated
