
npx squid-solana-typegen abi whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc#whirlpool
npx squid-solana-typegen abi Eo7WjKq67rjJQSZxS6z3YkapzY3eMj6Xy8X5EQVn5UaB#damm
npx squid-solana-typegen abi LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo#dlmm


